#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running validation

if ! command -v golangci-lint; then
    echo Skipping validation: no golangci-lint available
    exit
fi

echo Running: golangci-lint
export "GOROOT=$(go env GOROOT)"
golangci-lint run --fast --timeout=5m

