#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running validation

if ! command -v golangci-lint; then
    echo Skipping validation: no golangci-lint available
    exit
fi

echo Running: golangci-lint
golangci-lint run
