name: CI

on:
  pull_request: {}
  push:
    branches:
    - master
    - release/*

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6.5.2
      with:
        version: v1.64.8
        install-mode: goinstall
    - name: Run CI
      run: make build test
